on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Package and Distribute on PyPI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install numpy
          python setup.py build install
          pip install pytest
      - name : Running Tests
        run: |
          pytest
  package_and_distribute:
    name: Package and distribute
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install numpy
          python setup.py build install
          pip install build
          pip install twine
      - name: Install vsce in Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo npm install vsce -g
      - name: Install vsce in macOS
        if: matrix.os == 'macOS-latest'
        run: npm install vsce -g
      - name: Install vsce in Windows
        if: matrix.os == 'windows-latest'
        run: npm install vsce -g
      - name: Build, package and upload
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          ./dist.sh